#!/usr/bin/env ansible-playbook
# vim: noai:ts=2:sw=2:et
---

- name: "Test k5_network module"

  hosts: localhost
  connection: local
  gather_facts: no

  tasks:

    - k5_auth:
        username: "crossn"
        region_name: "uk-1"
      register: k5_auth_reg

    - debug: var=k5_auth_reg
    #- debug: var=k5_auth_reg.k5_auth_facts.auth_token

    - k5_create_network:
        name: "nx-test-net-1a"
        state: present
        availability_zone: "uk-1a"
        k5_auth: "{{ k5_auth_reg.k5_auth_facts }}"
      register: k5_network_reg

    - debug: var=k5_network_reg

    # rune twice so that we get a "already created error"
    - k5_create_network:
        name: "nx-test-net-1a"
        state: present
        availability_zone: "uk-1a"
        k5_auth: "{{ k5_auth_reg.k5_auth_facts }}"
      register: k5_network_reg

    - debug: var=k5_network_reg


